//
//  PasswordPromptScreen.swift
//  EcoJournalUITests
//
//  Screen object for the shared PasswordPromptSheet.
//
//  The sheet carries no accessibility identifiers, so elements are addressed
//  by their visible text and field placeholders.
//

import XCTest

struct PasswordPromptScreen {
    let app: XCUIApplication

    var title: XCUIElement {
        app.staticTexts["Enter Password"].firstMatch
    }

    /// The field toggles between secure and plain depending on the reveal
    /// button, so accept either.
    var passwordField: XCUIElement {
        let secure = app.secureTextFields["Enter password"].firstMatch
        return secure.exists ? secure : app.textFields["Enter password"].firstMatch
    }

    var unlockButton: XCUIElement {
        app.buttons["Unlock"].firstMatch
    }

    var incorrectPasswordMessage: XCUIElement {
        app.staticTexts["Incorrect password"].firstMatch
    }

    /// Lockout copy is generated by DashboardViewModel, e.g.
    /// "4 attempts remaining" or "Too many failed attempts…".
    func message(containing text: String) -> XCUIElement {
        app.staticTexts.containing(
            NSPredicate(format: "label CONTAINS[c] %@", text)
        ).firstMatch
    }
}
